language: csharp
branches:
  only:
    - master
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
  - mkdir build
  - bash build.sh
notifications:
  email:
    on_success: never
    on_failure: always